### ISSUE TITLE
PKCS#11 support

### ISSUE THREAD

**Issue by Yannovitch** [Yubico/ykneo-openpgp#17]
Hello,

I really, really would like to have PKCS#11 support in Yubikey and I understand it's possible to achieve that as stated in many posts on Yubico forums and website.
However I don't see it achieved anywhere so I'm looking for some ideas where to begin ?

Please help, even if just to drop quick and basic ideas.

Y

**Comment by Yannovitch** [comment]
Hello,
Now that I got a Yubikey Neo last generation, I would like to use the PIV applet with OpenSC for PKCS11 authentication into VeraCrypt (fork of TrueCrypt) to force the need of a Yubikey to decrypt my Volume.
My Yubikey & PIV applet is recognized by the OpenSC library that I specify in VeraCrypt.
However, when I try to use the opensc-pkcs11 library with Yubico inside VeraCrypt, I have an error saying "function not supported". 
Reading on your forum http://forum.yubico.com/viewtopic.php?p=7166&sid=958cdb2de8b74e2320955704d3765a12#p7166, I understand the problem come from OpenSC as it doesn't support objects like keyfiles.
I read on this post that there exist a PKCS11 library with OpenPGP. Do you know something about this option ?

Thanks, Y

**Comment by klali** [comment]
Hello,

This is a bugtracker for the openpgp applet of the Neo, for support requests you'll be better off with the forum or Yubico support.
However, it's very unlikely you'll want to use pkcs11 support with truecrypt, it breaks many assumptions about smartcards.

/klas

**Comment by mouse07410** [comment]
Klas,

I'd like to hear your opinion why you think that TrueCrypt with PKCS11 would break any assumptions about smart cards. I know that PIV and CAC cards are used to secure files - so why not file systems? And I think that there's a way to make BitLocker and FileVault-2 to unlock the drive via CAC...

Now this seems PIV applet-related rather than OpenPGP-related (though one probably can unlock flesh and file systems with PGP as well as with PIV?), so perhaps the OP chose a less-than-perfectly fitting mailing list to ask his question...

Sent from my iPad

On Apr 22, 2015, at 02:36, Klas Lindfors <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

This is a bugtracker for the openpgp applet of the Neo, for support requests you'll be better off with the forum or Yubico support.
However, it's very unlikely you'll want to use pkcs11 support with truecrypt, it breaks many assumptions about smartcards.

/klas

**Comment by klali** [comment]
So, the reason I think TrueCrypt's PKCS11 support breaks assumptions is that it uses data objects to store a key, instead of using crypto in the card. Used that way there's no difference between a usb drive and a smart card, except the smart card is alot clunkier to use.
There's nothing wrong with doing filesystem encryption with (to?) a smartcard like bitlocker or similar, the problem here lies in truecrypt.
